[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/dyhes"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"

[[social]]
identifier = "gmail"
name = "Gmail"
url = "mailto:dyheslin@gmail.com"

[social.params]
icon = "brand-gmail"